version: 2.1

executors:
  my-executor:
    docker:
      - image: sergioestebanp/basecontainer:1.0
jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: Run and Deploy the services
          working_directory: './DomoticPi_tools/cicd_server/'
          command: 'docker-compose up'
  test:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: Get testing code
          command: 'git clone https://github.com/SergioEstebanP/QA-Testing-Microservicios-Web.git'
      - run:
          name: Executing tests
          working_directory: './QA-Testing-Microservicios-Web'
          command: |
            ./gradlew clean test aggregate

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master