version: 2
jobs:
  build:
    docker:
      - image: sergioestebanp/domoticpi:testingThings-1.1
    steps:
      - checkout
      - run:
          name: Run and Deploy the services
          command: 'echo Hello-World'
  test:
    docker:
      - image: sergioestebanp/domoticpi:testingThings-1.1
    steps:
      - checkout
      - run:
          name: Get testing code
          command: 'git clone https://github.com/SergioEstebanP/QA-Testing-Microservicios-Web.git'
      - run:
          name: Executing tests
          working_directory: './QA-Testing-Microservicios-Web'
          command: |
            ./gradlew test 

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master