version: 2
jobs:
  build:
    docker:
      - image: sergioestebanp/domoticpi:testingThings
    steps:
      - checkout
      - run:
          name: Run and Deploy the services
          command: 'echo Hello-World'
  test:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Adding tools to the container
          command: |
            apt -y update 
            apt -y upgrade 
            apt install -y git
            apt install -y default-jdk
      - run:
          name: Get testing code
          command: 'git clone https://github.com/SergioEstebanP/QA-Testing-Microservicios-Web.git'
      - run:
          name: Executing tests
          working_directory: './QA-Testing-Microservicios-Web'
          command: |
            ls -la
            chmod u+x gradlew
            ls -la
            ./gradlew.sh clean test aggregate

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master