version: '2'

services:
  # DEVICE SERVICE
  device-service-db:
    build: ./device-service/db
    container_name: device-service-db
    ports: 
      - 3306:3306
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: device-service

  device-service:
    build: ./device-service
    container_name: device-service
    ports: 
      - 5000:5000
    networks:
      - backend

# HOUSE  SERVICE
  house-service-db:
    build: ./house-service/db
    container_name: house-service-db
    ports: 
      - 3306:3306
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: house-service

  house-service:
    build: ./house-service
    container_name: house-service
    ports: 
      - 5000:5000
    networks:
      - backend

networks:
  backend:
    driver: bridge
