version: '2'

services:
# DEVICE SERVICE
  device-service:
    build: ./device-service
    container_name: device-service
    ports: 
      - 6001:5000
    networks:
      - backend
      - frontend-services

# HOUSE SERVICE
  house-service:
    build: ./house-service
    container_name: house-service
    ports: 
      - 6002:5000
    networks:
      - backend
      - frontend-services

# USER SERVICE
  user-service:
    build: ./user-service
    container_name: user-service
    ports: 
      - 6003:5000
    networks:
      - backend
      - frontend-services

# DATABASE SERVICE
  database-service:
    build: ./database-service
    container_name: database-service
    ports: 
      - 7000:3306
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: database-service

# SERVICES FRONTEND
  services-frontend:
    build: ../DomoticPi_frontend
    container_name: services-frontend
    ports: 
      - 3001:3001
    networks:
      - frontend-services

networks:
  backend:
    driver: bridge
  frontend-services:
    driver: bridge