version: '2'

services:
  # HOUSE SERVICE
  house-service-db:
    build: ./house-service/db
    container_name: house-service-db
    ports: 
      - 7002:3306
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: house-service

  house-service:
    build: ./house-service
    container_name: house-service
    ports: 
      - 6002:5000
    networks:
      - backend

networks:
  backend:
    driver: bridge
