version: '2'

services:
  # USER SERVICE
  house-service-db:
    build: ./user-service/db
    container_name: user-service-db
    ports: 
      - 7003:3306
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: user-service

  user-service:
    build: ./user-service
    container_name: user-service
    ports: 
      - 6003:5000
    networks:
      - backend

networks:
  backend:
    driver: bridge
