version: '2'

services:
# BUSINESS FRONTEND
  business-frontend:
    build: .
    container_name: business-frontend
    ports: 
      - 3000:3000
    networks:
      - business

networks:
  business:
    driver: bridge
